theme: jekyll-theme-minimal
title: [Bebe]
description: [This is a joint webpage of bebe and bebe-shebe. Here the mornings start with "oye" and the night ends with kisses. The dream is to "bhangra" through life and live peacefully on a beach. We chose beach because it is both humbling and relaxing at the same time, plus the sea-food which bebe enjoys a lot.]
logo: /logo.png
mathjax: true

