theme: jekyll-theme-minimal
title: [Bebe]
description: [This is a joint webpage of bebe and bebe-shebe. Here the mornings start with "oye" and the night ends with kisses. The dream is to "bhangra" through life and live peacefully on a beach. We chose the beach because it is both humbling and relaxing at the same time. Moreover the bebes enjoy sea-food.]
logo: /logo.png
mathjax: true

